name: workflow

on: [push]

jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.11
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install --with=dev
        - name: Check formatting with Black
          run: |
            poetry run black .
        - name: Lint with ruff
          run: |
            poetry run ruff check .
